=== pierre-chevallier357/tux-letter-game/build/classes/xsd/profil.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           targetNamespace="http://myGame/tux"
           xmlns:tx="http://myGame/tux"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:element name="profils" type="tx:Profils"/>
    
    <xs:complexType name="Profils">
        <xs:sequence>
            <xs:element name="profil" type="tx:Profil"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Profil">
        <xs:sequence>
            <xs:element name="nom" type="tx:Nom"/>
            <xs:element name="avatar" type="tx:Avatar"/>
            <xs:element name="anniversaire" type="xs:date"/>
            <xs:element name="parties" type="tx:Parties"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="Nom">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z0-9àáâãäåçèéêëìíîïðòóôõöùúûüýÿ]{3,20}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="Avatar">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z0-9]{1,20}.(jpg|png|gif|jpeg)"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="Parties">
        <xs:sequence>
            <xs:element name="partie" type="tx:Partie" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Partie">
        <xs:sequence>
            <xs:element name="temps" type="tx:Temps" minOccurs="0" maxOccurs="1"/>
            <xs:element name="niveau" type="tx:Niveau"/>
        </xs:sequence>
        <xs:attribute name="date" type="xs:date"/>
        <xs:attribute name="trouvé" type="tx:Trouvé"/>
    </xs:complexType>
    
    <xs:complexType name="Niveau">
        <xs:sequence>
            <xs:element name="mot" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="difficulté" type="xs:int" use="required"  />
    </xs:complexType>
    
    
    
    <xs:simpleType name="Temps">
        <xs:restriction base="xs:double">
            <xs:minInclusive value="0.0"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="Trouvé">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{2}%"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== pierre-chevallier357/tux-letter-game/build/classes/xml/profil.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!--
    Document   : save_example.xml.xml
    Created on : August 31, 2014, 3:31 PM
    Author     : Johan Sarrazin / Céline Fouard / Nicolas Glade
    Description:
        Purpose of the document follows.
-->

<profils
    xmlns="http://myGame/tux" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://myGame/tux ../xsd/profil.xsd">
    
    <profil>
        <nom>Emmanuel</nom>
        <avatar>https://upload.wikimedia.org/wikipedia/commons/f/f4/Emmanuel_Macron_in_2019.jpg</avatar>
        <anniversaire>1977-12-21</anniversaire>
        <parties>
            <partie date="2013-12-10">
                <temps>20.0</temps>
                <niveau difficulté="1">
                    <mot>zoo</mot>
                </niveau>
            </partie>
            <partie date="2013-12-11" trouvé="75%">
                <niveau difficulté="2">
                    <mot>indice</mot>
                </niveau>
            </partie>
            <partie date="2013-12-11">
                <temps>30.0</temps>
                <niveau difficulté="2">
                    <mot>maman</mot>
                </niveau>
            </partie>
        </parties>
    </profil>
    
    <profil>
        <nom>Donald</nom>
        <avatar>https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Donald_Trump_official_portrait.jpg/946px-Donald_Trump_official_portrait.jpg</avatar>
        <anniversaire>1946-06-14</anniversaire>
        <parties>
            <partie date="2013-12-12">
                <temps>25.0</temps>
                <niveau difficulté="1">
                    <mot>vite</mot>
                </niveau>
            </partie>
            <partie date="2013-12-13" trouvé="50%">
                <niveau difficulté="2">
                    <mot>cousin</mot>
                </niveau>
            </partie>
            <partie date="2013-12-13">
                <temps>40.0</temps>
                <niveau difficulté="3">
                    <mot>chapiteau</mot>
                </niveau>
            </partie>
        </parties>
    </profil>
</profils>
